language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dexterdennis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dexterdennis/docker-react npm run test